In [61]:
# Manipulación de datos
import numpy as np
import pandas as pd

# Visualización
import matplotlib.pyplot as plt
import seaborn as sns

# Estadística
import scipy.stats as stats
import statsmodels.api as sm

# Preprocesamiento y selección de modelos
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, KFold
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Modelos
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.svm import SVC, SVR

# Métricas
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_auc_score, roc_curve,
    mean_squared_error, mean_absolute_error, r2_score,
)

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline
sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)

In [62]:
data = pd.read_csv("datos/df_clean.csv")
data.info()
data.head(20)

<class 'pandas.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   edad                       7500 non-null   int64
 1   genero                     7500 non-null   str
 2   horas_diarias_pantalla     7500 non-null   float64
 3   horas_redes_sociales       7500 non-null   float64
 4   horas_videojuegos          7500 non-null   float64
 5   horas_trabajo/estudio      7500 non-null   float64
 6   horas_sueño                7500 non-null   float64
 7   notificaciones_por_dia     7500 non-null   int64
 8   aperturas_apps_por_dia     7500 non-null   int64
 9   tiempo_pantalla_finde      7500 non-null   float64
 10  nivel_estres               7500 non-null   str
 11  impacto_academico/laboral  7500 non-null   str
 12  etiqueta_de_adiccion       7500 non-null   int64
 13  horas_ocio                 7500 non-null   float64
 14  ratio_finde_diario         7500 non-null   float64
 15  estado_adiccion            7500 non-null   str
 16  diferencia_finde           7500 non-null   float64
dtypes: float64(9), int64(4), str(4)
memory usage: 996.2 KB

,edad,genero,horas_diarias_pantalla,horas_redes_sociales,horas_videojuegos,horas_trabajo/estudio,horas_sueño,notificaciones_por_dia,aperturas_apps_por_dia,tiempo_pantalla_finde,nivel_estres,impacto_academico/laboral,etiqueta_de_adiccion,horas_ocio,ratio_finde_diario,estado_adiccion,diferencia_finde
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,0,2.90,1.222910,No adicto,0.72
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,0,6.05,1.318271,No adicto,1.62
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,0,5.19,1.432343,No adicto,2.62
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,1,7.36,1.247765,Adicto,1.94
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,1,9.34,1.260040,Adicto,2.59
5,26,Male,9.32,4.26,0.29,3.99,6.90,82,56,10.98,Medium,Yes,1,4.55,1.178112,Adicto,1.66
6,25,Male,10.40,4.93,1.60,0.86,8.61,165,95,11.43,Medium,No,1,6.53,1.099038,Adicto,1.03
7,26,Male,4.26,4.60,2.16,4.61,6.43,169,117,5.66,Low,No,1,6.76,1.328638,Adicto,1.40
8,21,Other,4.38,1.38,2.72,3.78,6.23,172,134,6.20,High,Yes,0,4.10,1.415525,No adicto,1.82
9,35,Other,9.76,4.73,1.36,2.11,5.21,20,82,12.69,Low,Yes,1,6.09,1.300205,Adicto,2.93
10,34,Female,8.48,1.34,3.05,3.47,8.00,155,15,10.48,Medium,Yes,1,4.39,1.235849,Adicto,2.00
11,27,Other,5.16,1.82,2.27,0.93,7.79,228,32,8.10,High,Yes,0,4.09,1.569767,No adicto,2.94
12,33,Other,11.52,1.41,2.11,3.84,8.84,158,66,13.80,Medium,No,1,3.52,1.197917,Adicto,2.28
13,32,Male,4.09,1.74,1.35,3.74,5.54,76,16,4.77,High,Yes,0,3.09,1.166259,No adicto,0.68
14,19,Male,10.74,0.89,0.95,4.18,5.46,53,161,12.68,Low,No,1,1.84,1.180633,Adicto,1.94
15,21,Male,3.87,2.87,1.69,3.07,7.78,192,180,4.62,Medium,No,0,4.56,1.193798,No adicto,0.75
16,24,Other,4.71,2.97,1.69,2.03,5.62,39,128,7.23,High,Yes,0,4.66,1.535032,No adicto,2.52
17,35,Female,10.52,5.83,3.71,5.17,5.25,144,138,11.55,Medium,Yes,1,9.54,1.097909,Adicto,1.03
18,18,Female,11.87,1.96,3.14,3.00,6.40,207,157,14.02,Medium,Yes,1,5.10,1.181129,Adicto,2.15
19,24,Other,11.72,3.69,2.17,4.61,4.76,169,137,13.48,High,Yes,1,5.86,1.150171,Adicto,1.76

### Aplicando label encoding para las variables booleanas:

In [63]:
data['impacto_academico/laboral'] = data['impacto_academico/laboral'].map({'No': 0, 'Yes': 1})
data['estado_adiccion'] = data['estado_adiccion'].map({'No adicto': 0, 'Adicto': 1})
data.drop('etiqueta_de_adiccion', axis=1, inplace=True) #Eliminamos la columna etiqueta de adiccion que sería suplantada por 'estado_adiccion'


print("DataFrame después de Label Encoding:")
data.head()

DataFrame después de Label Encoding:

,edad,genero,horas_diarias_pantalla,horas_redes_sociales,horas_videojuegos,horas_trabajo/estudio,horas_sueño,notificaciones_por_dia,aperturas_apps_por_dia,tiempo_pantalla_finde,nivel_estres,impacto_academico/laboral,horas_ocio,ratio_finde_diario,estado_adiccion,diferencia_finde
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,1,2.90,1.222910,0,0.72
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,1,6.05,1.318271,0,1.62
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,0,5.19,1.432343,0,2.62
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,1,7.36,1.247765,1,1.94
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,0,9.34,1.260040,1,2.59

### Aplicamos One-Hot Encoding para `nivel_estres`:

In [64]:
data = pd.get_dummies(data, columns=['nivel_estres'], drop_first=True)
data['nivel_estres_Low'] = data['nivel_estres_Low'].astype(int)
data['nivel_estres_Medium'] = data['nivel_estres_Medium'].astype(int)

print("DataFrame después de One-Hot Encoding:")
data.head(20)

DataFrame después de One-Hot Encoding:

,edad,genero,horas_diarias_pantalla,horas_redes_sociales,horas_videojuegos,horas_trabajo/estudio,horas_sueño,notificaciones_por_dia,aperturas_apps_por_dia,tiempo_pantalla_finde,impacto_academico/laboral,horas_ocio,ratio_finde_diario,estado_adiccion,diferencia_finde,nivel_estres_Low,nivel_estres_Medium
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,1,2.90,1.222910,0,0.72,0,1
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,1,6.05,1.318271,0,1.62,0,1
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,0,5.19,1.432343,0,2.62,0,0
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,1,7.36,1.247765,1,1.94,0,0
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,0,9.34,1.260040,1,2.59,1,0
5,26,Male,9.32,4.26,0.29,3.99,6.90,82,56,10.98,1,4.55,1.178112,1,1.66,0,1
6,25,Male,10.40,4.93,1.60,0.86,8.61,165,95,11.43,0,6.53,1.099038,1,1.03,0,1
7,26,Male,4.26,4.60,2.16,4.61,6.43,169,117,5.66,0,6.76,1.328638,1,1.40,1,0
8,21,Other,4.38,1.38,2.72,3.78,6.23,172,134,6.20,1,4.10,1.415525,0,1.82,0,0
9,35,Other,9.76,4.73,1.36,2.11,5.21,20,82,12.69,1,6.09,1.300205,1,2.93,1,0
10,34,Female,8.48,1.34,3.05,3.47,8.00,155,15,10.48,1,4.39,1.235849,1,2.00,0,1
11,27,Other,5.16,1.82,2.27,0.93,7.79,228,32,8.10,1,4.09,1.569767,0,2.94,0,0
12,33,Other,11.52,1.41,2.11,3.84,8.84,158,66,13.80,0,3.52,1.197917,1,2.28,0,1
13,32,Male,4.09,1.74,1.35,3.74,5.54,76,16,4.77,1,3.09,1.166259,0,0.68,0,0
14,19,Male,10.74,0.89,0.95,4.18,5.46,53,161,12.68,0,1.84,1.180633,1,1.94,1,0
15,21,Male,3.87,2.87,1.69,3.07,7.78,192,180,4.62,0,4.56,1.193798,0,0.75,0,1
16,24,Other,4.71,2.97,1.69,2.03,5.62,39,128,7.23,1,4.66,1.535032,0,2.52,0,0
17,35,Female,10.52,5.83,3.71,5.17,5.25,144,138,11.55,1,9.54,1.097909,1,1.03,0,1
18,18,Female,11.87,1.96,3.14,3.00,6.40,207,157,14.02,1,5.10,1.181129,1,2.15,0,1
19,24,Other,11.72,3.69,2.17,4.61,4.76,169,137,13.48,1,5.86,1.150171,1,1.76,0,0

Ahora procederemos a limpiar el dataset para quedarnos unicamente con las variables que sirvan para el modelo predictivo:

In [65]:
data.drop('tiempo_pantalla_finde', axis=1, inplace=True) #Aporta informacion muy similar a la pantalla diaria
data.drop('ratio_finde_diario', axis=1, inplace=True) # relacionado a tiempo_pantalla_finde
data.drop('diferencia_finde', axis=1, inplace=True) # relacionado a tiempo_pantalla_finde
data.drop('horas_ocio', axis=1, inplace=True) #Unicamente para explorar, tiene menos relacion que redes sociales sola
data.head()

,edad,genero,horas_diarias_pantalla,horas_redes_sociales,horas_videojuegos,horas_trabajo/estudio,horas_sueño,notificaciones_por_dia,aperturas_apps_por_dia,impacto_academico/laboral,estado_adiccion,nivel_estres_Low,nivel_estres_Medium
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,1,0,0,1
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,1,0,0,1
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,0,0,0,0
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,1,1,0,0
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,0,1,1,0